### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by pickbreaker** [MSeifert04/iteration_utilities#208]
When installing with pyCharm:
https://pastebin.com/vGCEJNUY

With cmd and powerShell:
https://pastebin.com/5BX7761Y

With pip same error

**Comment by MSeifert04** [comment]
That's a common error when you don't have a C compiler in your path. `iteration_utilities` isn't a pure Python package so it requires that you have a C compiler (http://iteration-utilities.readthedocs.io/en/latest/installation.html#dependencies). 

You might find some information for example on StackOverflow: https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed

Or if you don't want to install and setup a C compiler you can install conda/anaconda and then use the `conda` command to install it: `conda install -c conda-forge iteration_utilities` (or install it with conda in PyCharm)

**Comment by pickbreaker** [comment]
Thanks, wanted to install a c compiler anyway.
