### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [MSeifert04/iteration_utilities#331]
Problem
---------
On aarch64, `pip install iteration_utilities` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install iteration_utilities` should download the wheels from PyPI.

@MSeifert04, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by MSeifert04** [comment]
Version 0.12.0 includes a lot of additional wheels for different platforms (maybe one of them works for aarch64, I don't think so but there's a chance). 

Additional environments in the CI/CD also have to be maintained and that's something I simply don't want to do.
