### ISSUE TITLE
Could not install with pip

### ISSUE THREAD

**Issue by pedropaulofb** [MSeifert04/iteration_utilities#335]
Hi! First of all, thank you for your library.

I tried to install it using the pip command (`pip install iteration-utilities`), however I had no success. The result can be found below.

I am new to Python, so I don't know exactly if this is something to do with the library or not, but it seems to be a library problem ("_note: This is an issue with the package mentioned above, not pip._"). Maybe this feedback can be useful for improvements.

```cmd
× Running setup.py install for iteration-utilities did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running install
      C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\_additional_recipes.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\_classes.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\_convenience.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\_recipes.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\_utils.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      copying src\iteration_utilities\__init__.py -> build\lib.win-amd64-cpython-310\iteration_utilities
      running build_ext
      building 'iteration_utilities._iteration_utilities' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> iteration-utilities

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

By the way, I'm using Python 3.10.5 on Windows.

**Comment by cjc2000** [comment]
Hello, some package in python like wordcloud have to install Microsoft Visual Studio 2015 or above. You can try the link https://visualstudio.microsoft.com/visual-cpp-build-tools/ to download and install, then the problem might be fixed. Or you can try the lower version of Python like Python 3.6 or Python 3.7 to avoid that problem.

**Comment by blakeNaccarato** [comment]
See [my comment](https://github.com/copier-org/copier/issues/610#issuecomment-1110244031) in another repo where a similar problem was encountered. One way to do it is as follows:

> Install MSVC C++ build tools: Coincidentally, following the "Prerequisites" section of [this guide](https://code.visualstudio.com/docs/cpp/config-msvc#_prerequisites) will give Windows users the proper build tools. So, follow that guide and reboot Windows, then e.g. `py -3.10 -m pipx install copier` should work.

Alternatively: 

> Download the wheel appropriate for your architecture from these [build artifacts](https://github.com/MSeifert04/iteration_utilities/actions/runs/2008739611). Create a `pipx` environment and inject this wheel into it, then install copier into that same environment. This workaround will expire at some point, as workflow run artifacts are not available indefinitely.

**Comment by MSeifert04** [comment]
Thanks for reporting the issue. I just uploaded a new version that includes already compiled wheels, including for Windows with Python 3.10. I hope this will resolve your issue.
