### ISSUE TITLE
DEPRECATION on setup.py

### ISSUE THREAD

**Issue by dmidlo** [MSeifert04/iteration_utilities#338]
pip reports the following warning on install.

`DEPRECATION: iteration-utilities is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559`

**Comment by MSeifert04** [comment]
Thanks for reporting the problem. This should be fixed with the newest version.
