### ISSUE TITLE
PyPI source missing test helper modules

### ISSUE THREAD

**Issue by bcbnz** [MSeifert04/iteration_utilities#344]
The source tarball available on PyPI includes the `test_*.py` files, but not `conftest.py`, `helper_cls.py` or `helper_funcs.py`. This means the tests cannot be run from this tarball.

**Comment by MSeifert04** [comment]
Hi @bcbnz thanks for opening the issue. 

I can confirm that there are some files missing from the tests folder and i'm currently working on a commit to fix this.
